__title__ = 'pretorched'
__description__ = 'PyTorch utilities for neural network research.'
__url__ = 'https://github.com/moyiliyi/pretorched-x'
__version__ = '0.1.dev1.clf'
__author__ = 'Lufan Chang'
__email__ = 'changlufan@gmail.com'
__license__ = 'MIT'
__keywords__ = 'pytorch deep learning pretrained models utilities'
